### ISSUE TITLE
Add ability to distinguish left and right modifiers?

### ISSUE THREAD

**Issue by es183923** [dbalatero/HyperKey.spoon#1]
It would be nice to be able to use hyper key with extra modifiers.

**Comment by dbalatero** [comment]
That's not a super high priority feature for me, but if you wanted to submit a PR I'd merge it.

You'd want to use the raw flags instead:

* https://www.hammerspoon.org/docs/hs.eventtap.event.html#rawFlags
* https://www.hammerspoon.org/docs/hs.eventtap.event.html#rawFlagMasks

_but_ the caveat is that you can't break the current interface for building a `HyperKey`, which currently takes a table of modifiers like so:

```lua
hyperKey = HyperKey:new({'cmd','shift','ctrl','alt'})
-- or
hyperKey = HyperKey:new({'cmd','shift','ctrl','alt'}, { ...extra options })
```

You'd need to figure out how to keep this API shape while making left/right modifiers "work".

* Do you take variable arguments to the constructor?
* Do you create a different constructor for raw flags mode?
* Do you add an extra option to the 2nd parameter?
* Do you add new modifier flags like `{'left cmd', 'right alt'}`?

If you're up for the work let me know. If you're not up for it, please also let me know so we can close the ticket out.

**Comment by es183923** [comment]
I'll take a look into doing it.  I might be have time to do it, but I'm not sure.
